services:
  jupyter-pyspark:
    build:
      context: docker/
      args:
        spark_version: "3.4.4"
        scala_version: "2.13"
    restart: unless-stopped
    env_file:
      - ../.env-local
    ports:
      - "8888:8888"  # (Jupyter Notebook)
      - "4040:4040"  # (TensorBoard)
      - "4041:4041"  # (Spark UI)
      - "4042:4042"  # (Spark History Server)
    volumes:
      - ./examples:/home/jovyan/examples:rw

volumes:
  jupyter-pyspark-data:

