services:

  setup:
    image: debian:stable-slim
    env_file:
      - path: ../.env-local
        required: true
      - path: ./.env
        required: true
    volumes:
      - nar_extensions:/mnt/jars
      - ./setup.sh:/workspace/setup.sh
    command: >
      bash /workspace/setup.sh

  nifi:
    image: apache/nifi:${NIFI_VERSION}
    restart: unless-stopped
    platform: linux/amd64
    container_name: nifi
    depends_on:
      setup:
        condition: service_completed_successfully
    env_file:
      - path: ../.env-local
        required: true
      - path: ./.env
        required: true
    ports:
      - ${EXT_NIFI_PORT}:8443
    volumes:
      - nar_extensions:/opt/nifi/nifi-current/nar_extensions:rw
      - state:/opt/nifi/nifi-current/state:rw
      - database_repository:/opt/nifi/nifi-current/database_repository:rw
      - flowfile_repository:/opt/nifi/nifi-current/flowfile_repository:rw
      - content_repository:/opt/nifi/nifi-current/content_repository:rw
      - provenance_repository:/opt/nifi/nifi-current/provenance_repository:rw
      - ./healthcheck.sh:/healthcheck.sh
      - ./assets:/assets/
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      retries: 10

volumes:
  nar_extensions:
  state:
  database_repository:
  flowfile_repository:
  content_repository:
  provenance_repository:
