services:

  verify_required_env:
    image: hairyhenderson/gomplate:latest
    working_dir: /workspace
    env_file:
      - ./.env
      - ../.env-local
    command: "-i '{{env.Getenv \"DOCKER_HOST_OR_IP\" | required \"Mandatory DOCKER_HOST_OR_IP environment variable not found.\"}}'"

  setup_jars:
    image: debian:stable-slim
    depends_on:
      verify_required_env:
        condition: service_completed_successfully
    env_file:
      - ./.env
      - ../.env-local
    volumes:
      - ./nifi_extensions:/mnt/jars
      - ./setup_jars.sh:/workspace/setup_jars.sh
    command: >
      bash /workspace/setup_jars.sh

  nifi:
    image: apache/nifi:${NIFI_VERSION}
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      verify_required_env:
        condition: service_completed_successfully
      setup_jars:
        condition: service_completed_successfully
    env_file:
      - path: ./.env
        required: true
      - path: ../.env-local
        required: true
    ports:
      - ${EXT_NIFI_PORT}:8443
    volumes:
      - ./nifi_extensions:/opt/nifi/nifi-current/nar_extensions:rw
      - ./nifi_state:/opt/nifi/nifi-current/state:rw
      - ./nifi_db:/opt/nifi/nifi-current/database_repository:rw
      - ./nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository:rw
      - ./nifi_content:/opt/nifi/nifi-current/content_repository:rw
      - ./nifi_provenance:/opt/nifi/nifi-current/provenance_repository:rw