services:

  setup:
    image: alpine:latest
    environment:
      - NIFI_HOST=${NIFI_HOST}
    command: >
      ash -c "if [ -n \"$NIFI_HOST\" ]; then
               echo 'NIFI_HOST is set: \$NIFI_HOST';
               exit 0;
             else
               echo 'Mandatory NIFI_HOST environment is not set.  Quiting.';
               exit 1;
             fi"

  nifi:
    image: apache/nifi:${NIFI_VERSION}
    platform: linux/amd64
    depends_on:
      setup:
        condition: service_completed_successfully
    environment:
      - NIFI_WEB_PROXY_HOST=${NIFI_HOST}
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456123456
    ports:
      - "${NIFI_PORT:-18443}:8443"
    volumes:
      - ./nifi_extensions:/opt/nifi/nifi-current/nar_extensions:rw
      - ./nifi_state:/opt/nifi/nifi-current/state:rw
      - ./nifi_db:/opt/nifi/nifi-current/database_repository:rw
      - ./nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository:rw
      - ./nifi_content:/opt/nifi/nifi-current/content_repository:rw
      - ./nifi_provenance:/opt/nifi/nifi-current/provenance_repository:rw