services:
  nifi:
    image: apache/nifi:${NIFI_VERSION}
    platform: linux/amd64
    environment:
      - NIFI_WEB_PROXY_HOST=${NIFI_HOST}
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=123456123456
    ports:
      - "8443:8443"
    volumes:
      - ./nifi_extensions:/opt/nifi/nifi-current/nar_extensions:rw
      - ./nifi_state:/opt/nifi/nifi-current/state:rw
      - ./nifi_db:/opt/nifi/nifi-current/database_repository:rw
      - ./nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository:rw
      - ./nifi_content:/opt/nifi/nifi-current/content_repository:rw
      - ./nifi_provenance:/opt/nifi/nifi-current/provenance_repository:rw