version: '3.9'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/hive-db:/var/lib/postgresql
    networks:
      - hive

  metastore:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    env_file: .env-local
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
      HIVE_CUSTOM_CONF_DIR: /opt/hive/custom_conf
    ports:
      - '9083:9083'
    volumes:
      - ./volumes/warehouse:/opt/hive/data/warehouse
      - ./custom_conf/:/opt/hive/custom_conf/
      - ./jars/hadoop-aws.jar:/opt/hive/lib/hadoop-aws.jar
      - ./jars/aws-java-sdk-bundle.jar:/opt/hive/lib/aws-sdk-bundle.jar
      - ./jars/postgresql.jar:/opt/hive/lib/postgresql.jar
    networks:
      - hive

  hiveserver2:
    image: apache/hive:${HIVE_VERSION}
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    env_file: .env-local
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
      HIVE_CUSTOM_CONF_DIR: /opt/hive/custom_conf
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - ./volumes/warehouse:/opt/hive/data/warehouse
      - ./custom_conf/:/opt/hive/custom_conf/
      - ./jars/hadoop-aws.jar:/opt/hive/lib/hadoop-aws.jar
      - ./jars/aws-java-sdk-bundle.jar:/opt/hive/lib/aws-sdk-bundle.jar
    networks:
      - hive

networks:
  hive:
    name: hive
