name: redpanda-quickstart-one-broker
networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda-0: null
services:

  setup_config:
    image: hairyhenderson/gomplate:latest
    working_dir: /workspace
    env_file:
      - ../.env-local
    volumes:
      - ./templates:/workspace/templates
      - ./generated:/workspace/output
    command: "-f /workspace/templates/redpanda.yml -o /workspace/output/redpanda.yml"

  redpanda-0:
    command:
      - redpanda
      - start
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
      - --config /tmp/redpanda.yml
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.8
    container_name: redpanda-0
    restart: unless-stopped
    depends_on:
      setup_config:
        condition: service_completed_successfully
    volumes:
      - redpanda-0:/var/lib/redpanda/data
      - ./generated/redpanda.yml:/tmp/redpanda.yml
    networks:
      - redpanda_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    restart: unless-stopped
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
    ports:
      - 28080:8080
    depends_on:
      - redpanda-0

# name: redpanda-quickstart-one-broker
# networks:
#   redpanda_network:
#     driver: bridge
# volumes:
#   redpanda-0: null
# services:
#   redpanda-0:
#     command:
#       - redpanda
#       - start
#       - --node-id 0
#       - --smp 1
#       - --memory 1G
#       - --overprovisioned
#     image: docker.redpanda.com/redpandadata/redpanda:v24.2.8
#     restart: unless-stopped
#     container_name: redpanda-0
#     volumes:
#       - redpanda-0:/var/lib/redpanda/data
#       - ./redpanda.yaml:/var/lib/redpanda/.config/rpk/redpanda.yaml:ro
#     networks:
#       - redpanda_network
#     ports:
#       - 18081:18081
#       - 18082:18082
#       - 19092:19092
#       - 19644:9644

#   console:
#     container_name: redpanda-console
#     restart: unless-stopped
#     image: docker.redpanda.com/redpandadata/console:v2.7.2
#     networks:
#       - redpanda_network
#     entrypoint: /bin/sh
#     command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
#     environment:
#       CONFIG_FILEPATH: /tmp/config.yml
#       CONSOLE_CONFIG_FILE: |
#         kafka:
#           brokers: ["redpanda-0:9092"]
#           schemaRegistry:
#             enabled: true
#             urls: ["http://redpanda-0:8081"]
#         redpanda:
#           adminApi:
#             enabled: true
#             urls: ["http://redpanda-0:9644"]
#     ports:
#       - 8080:8080
#     depends_on:
#       - redpanda-0
